name: daily
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.1
  provider: ^6.0.5
  flutter_slidable: ^3.0.0
  mockito: ^5.4.5
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^0.13.6
  


flutter:
  uses-material-design: true
